[workspace]
members = [
    "actions/common",
    "actions/event-registration",
    "actions/balance-notification-registration",
    "actions/balance-filter",
    "actions/push-notification",
    "actions/event-receiver",
    "actions/substrate-event-processor",
    "workflow/openwhisk_macro"
]